// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72Vw7I71nnJn1HNx6QSs3hieTXtQ-lIw',
    appId: '1:1035350030530:web:5b0f61a112ba10077e635b',
    messagingSenderId: '1035350030530',
    projectId: 'abbmobileapp1',
    authDomain: 'abbmobileapp1.firebaseapp.com',
    storageBucket: 'abbmobileapp1.firebasestorage.app',
    measurementId: 'G-9MBBPXYDX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_h0osXJYD60FMtgfj9i_FpXu5MPBevDI',
    appId: '1:1035350030530:android:5d5b4c7ea7a1d70b7e635b',
    messagingSenderId: '1035350030530',
    projectId: 'abbmobileapp1',
    storageBucket: 'abbmobileapp1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRkkIGTyAUHyMlH8NRI0hElWHUrzvzQM',
    appId: '1:1035350030530:ios:da9a705f9db4dc447e635b',
    messagingSenderId: '1035350030530',
    projectId: 'abbmobileapp1',
    storageBucket: 'abbmobileapp1.firebasestorage.app',
    iosBundleId: 'com.example.abbUserApp',
  );
}
